kind: pipeline
name: default

limit:
  concurrency: 1
  per_branch: true

steps:
- name: build android
  image: xennitee/android-docker-image:0
  volumes:
  - name: cache
    path: /data/drone/cache
  commands:
    - pwd
    - ./gradlew assembleDebug
    - ls src/android-client/build/
    - ls src/android-client/build/outputs/
    - ls src/android-client/build/outputs/apk/
    - ls src/android-client/build/outputs/apk/debug/
    - ls src/android-client/build/outputs/apk/debug/*.apk
  when:
    event: pull_request
    branch:
      exclude: master
- name: temp volume catch test
  image: xennitee/android-docker-image:0
  volumes:
  - name: cache
    path: /data/drone/cache
  commands:
    - ls src/android-client/build/outputs/apk/debug/*.apk
  when:
    event: pull_request
    branch:
      exclude: master

- name: android output
  image: xennitee/android-docker-image:0
  volumes:
  - name: cache
    path: /data/drone/cache/outputs
  commands:
    - ./gradlew assembleDebug
    - mv src/android-client/build/outputs/apk/debug/*.apk /data/drone/cache/outputs
  when:
    event:
    - tag

- name: publish to github release
  image: plugins/github-release
  settings:
    api_key: 11d402907387d60538d18edb98f45262c2427a64
    files: /data/drone/outputs/*.apk
    draft: true
    prerelease: true
    note: src/android-client/CHANGELOG.md
    overwrite: true
  when:
    event:
    - tag
