kind: pipeline
name: default

limit:
  concurrency: 1
  per_branch: true

steps:
- name: build android
  image: xennitee/android-docker-image:0
  commands:
    - ./gradlew assembleDebug
- name: publish to github release
  image: plugins/github-release
  settings:
    api_key: /root/.ssh/id_rsa
    files: src/android-client/build/outputs/apk/debug/*.apk
    prerelease: true
    note: src/android-client/CHANGELOG.md
  when:
    event: tag
