kind: pipeline
name: default

limit:
  concurrency: 1
  per_branch: true

steps:
- name: build android
  image: xennitee/android-docker-image:0
  volumes:
  - name: cache
    path: /data/drone/cache/
  commands:
    - ls -al
    - ./gradlew buildDebug
  when:
    event: pull_request
    branch:
      exclude: master

- name: android output
  image: xennitee/android-docker-image:0
  volumes:
  - name: cache
    path: /data/drone/cache/
  commands:
    - ./gradlew assembleRelease
  when:
    event:
    - tag

- name: publish to github release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_release_token
    files: src/android-client/build/outputs/apk/release/*.apk
    draft: true
    prerelease: true
    note: src/android-client/CHANGELOG.md
    overwrite: true
  when:
    event:
    - tag

volumes:
- name: cache
  host:
    path: /data/drone/.android
