kind: pipeline
name: default

limit:
  concurrency: 1
  per_branch: true

steps:
- name: build android
  image: xennitee/android-docker-image:0
  commands:
    - ./gradlew assembleDebug

- name: publish to github release
  image: plugins/github-release
  settings:
    api_key: 11d402907387d60538d18edb98f45262c2427a64
    files: src/android-client/build/outputs/apk/debug/*.apk
    draft: true
    prerelease: true
    note: src/android-client/CHANGELOG.md
  when:
    branch:
    - master
