kind: pipeline
name: default

limit:
  concurrency: 1
  per_branch: true

steps:
- name: build android
  image: xennitee/android-docker-image:0
  volumes:
  - name: cache
    path: /data/drone/cache/
  commands:
    - ./gradlew buildDebug
  when:
    event: pull_request
    branch:
      exclude: master

- name: android output
  image: xennitee/android-docker-image:0
  volumes:
  - name: cache
    path: /data/drone/cache/
  commands:
    - mkdir src/android-client/build/outputs/apk/debug/xxxxxx.apk
  when:
    event:
    - tag

- name: publish to github release
  image: plugins/github-release
  settings:
    api_key: a9b42701f53f21f777270c2e11a69fffdba54828
    files: src/android-client/build/outputs/apk/debug/*.apk
    draft: true
    prerelease: true
    note: src/android-client/CHANGELOG.md
    overwrite: true
  commands:
    - env
  when:
    event:
    - tag
