kind: pipeline
name: default

limit:
  concurrency: 1
  per_branch: true

steps:
- name: build android
  image: xennitee/android-docker-image:0
  commands:
    - ./gradlew buildDebug

steps:
- name: build android
  image: xennitee/android-docker-image:0
  volumes:
  - name: cache
    path: /data/drone/pipeline_cache/outputs
  commands:
    - ./gradlew assembleDebug
    - mv src/android-client/build/outputs/apk/debug/*.apk /data/drone/outputs/
  when:
    event:
    - tag

- name: publish to github release
  image: plugins/github-release
  settings:
    api_key: 11d402907387d60538d18edb98f45262c2427a64
    files: /data/drone/outputs/*.apk
    draft: true
    prerelease: true
    note: src/android-client/CHANGELOG.md
    overwrite: true
  when:
    event:
    - tag
